// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/hero-variants/HeroV1.tsx": () => import("../components/mockups/hero-variants/HeroV1.tsx"),
  "./components/mockups/hero-variants/HeroV2.tsx": () => import("../components/mockups/hero-variants/HeroV2.tsx"),
  "./components/mockups/hero-variants/HeroV3.tsx": () => import("../components/mockups/hero-variants/HeroV3.tsx"),
  "./components/mockups/hero-variants/HeroV4.tsx": () => import("../components/mockups/hero-variants/HeroV4.tsx"),
  "./components/mockups/hero-variants/HeroV5.tsx": () => import("../components/mockups/hero-variants/HeroV5.tsx")
};
